encoding: UTF-8

url:              http://codn.github.io/adminpanel/
# url:              http://localhost:4000/adminpanel/
baseurl: /adminpanel

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none
relative_permalinks: true

defaults:
  -
    scope:
      path: 'generators'
    values:
      layout: 'post'

  -
    scope:
      path: 'modules'
    values:
      layout: 'post'

  -
    scope:
      path: 'sections'
    values:
      layout: 'post'
