encoding: UTF-8

url:              https://codn.github.io/adminpanel/
# url:              http://localhost:4000/adminpanel/
baseurl: /adminpanel

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none
