# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../dummy/config/environment", __FILE__)
require "rspec/rails"
require "capybara/rspec"
require "factory_girl_rails"
require 'carrierwave/orm/activerecord'
require "carrierwave/test/matchers"
require "active_record"
require "rake"


Dir["./spec/support/**/*.rb"].sort.each { |f| require f }

# FactoryGirl.find_definitions
RSpec.configure do |config|
	config.treat_symbols_as_metadata_keys_with_true_values = true
	config.run_all_when_everything_filtered = true
	config.filter_run :focus

	# root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
	ActiveRecord::Base.establish_connection(
	  :adapter => 'sqlite3',
	  :database => ':memory:'
	)

	config.include ActionDispatch::TestProcess

	puts "creating sqlite in memory database"
	load "#{Rails.root}/db/schema.rb"

	config.use_transactional_fixtures = false

	config.include Rails.application.routes.url_helpers

	config.order = 'random'
end
