# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../dummy/config/environment", __FILE__)
require "rspec/rails"
require "factory_girl"

Dir["./spec/support/**/*.rb"].sort.each {|f| require f}

Factory.define :user, :class => Adminpanel::User do |u|
	u.name "test user"
	u.email "email@test.com"
	u.password "123456"
	u.password_confirmation "123456"
end

RSpec.configure do |config|
	config.treat_symbols_as_metadata_keys_with_true_values = true
	config.run_all_when_everything_filtered = true
	config.filter_run :focus

	root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
	ActiveRecord::Base.establish_connection(
	  :adapter => 'sqlite3',
	  :database => ':memory:'
	)

	config.include Rails.application.routes.url_helpers
	# config.before(:each, :type => :routing)    { @routes = Utilizer::Engine.routes }
	# Run specs in random order to surface order dependencies. If you find an
	# order dependency and want to debug it, you can fix the order by providing
	# the seed, which is printed after each run.
	#     --seed 1234
	config.order = 'random'
end
